CREATE TABLE MENU (
  NAME VARCHAR(100) NOT NULL ,
  DESCRIPTION VARCHAR(250) NOT NULL ,
  IMAGE VARCHAR(100) NOT NULL ,
  PRICE INTEGER NOT NULL ,
  ADDITIONAL VARCHAR(250) ,
  PRIMARY KEY (NAME)
);

CREATE TABLE CUSTOMER_ORDER (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT ,
  BILL_NO VARCHAR(20) NOT NULL ,
  MENU VARCHAR(250) NOT NULL ,
  QUANTITY INTEGER NOT NULL ,
  ORDERED_TIME TIMESTAMP NOT NULL ,
  CHECKED_OUT NUMBER(1) NOT NULL
);